# -*- coding: utf-8 -*-
"""code for chess temp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1amEii-zbY5UW-G88FjTzguGEPWcdNl_Z
"""

! pip install python-chess

import chess

def display_board(board):
    print(board)

def main():
    board = chess.Board()

    while not board.is_game_over():
        display_board(board)
        move_uci = input("Enter your move in UCI format (e.g., e2e3, e2e4): ")

        try:
            chess_move = chess.Move.from_uci(move_uci)
            if chess_move in board.legal_moves:
                board.push(chess_move)
            else:
                print("Invalid move. Try again.")
        except ValueError:
            print("Invalid input. Try again.")

    display_board(board)
    print("Game over. Result:", board.result())

if __name__ == "__main__":
    main()

python chess_movement_with_board.py

